site_name: Data Management
theme:
  name: 'material'

# Project information
site_name: Data Management
site_description: Data Management
site_author: HyperJ
site_url: https://hyperj.github.io/docs.data-management/

# Repository
repo_name: hyperj/docs.data-management
repo_url: https://github.com/hyperj/docs.data-management
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2009 - 2018 HyperJ'

# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/favicon.ico

# Customization
extra:
  social:
    - type: github-alt
      link: https://gist.github.com/hyperj/
    - type: github
      link: https://github.com/hyperj
    - type: h-square
      link: http://blog.hyperj.net
    - type: linkedin
      link: https://www.linkedin.com/in/hyperj

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Data Governance: data-governance.md
  - Data Architecture: data-architecture.md
  - Data Modeling & Design: data-modeling-and-design.md
  - Data Storage & Operations: data-storage-and-operations.md
  - Data Security: data-security.md
  - Data Integration & Interoperability: data-integration-and-interoperability.md
  - Documents & Content: documents-and-content.md
  - Reference & Master Data: reference-and-master-data.md
  - Data Warehousing & Business Intelligence: data-warehousing-and-business-intelligence.md
  - Metadata: metadata.md
  - Data Quality: data-quality.md
  - Practice:
    - Work & Practice: work-and-practice.md
    - Projects & Articles: projects-and-articles.md


# Analytics


